backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "headerImage", name: "headerImage", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Carousel", name: "Carousel", widget: list, fields:[
          {label: "slide", name: "slide", widget: "image", required: false }]}
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Text Left", name: "txtLeft", widget: "markdown", required: false}
      - { label: "Image right", name: "imgRight", widget: "image", required: false}
      - { label: "blurbs", name: "blurbs", widget: list, fields:[
            {label: "image", name: "blurbImg", widget: "image", required: false},
            {label: "texte", name: "blurbTxt", widget: "text", required: false}]}
      - { label: "bloques", name: "blocks", widget: list, fields:[
          { label: "Image seule", name: "imgOnly", widget: "image", required: false},
          { label: "Text seul", name: "txtOnly", widget: "markdown", required: false},
          { label: "Texte et image", name: "txtLImgR", widget: "object", fields:
            -{ label: "Texte", name: "txtL", widget: "markdown", required: false}
            -{ label: "Image", name: "imgR", widget: "image", required: false}},
          { label: "Image et texte", name: "txtRImgL", widget: "object", fields:
            -{ label: "Image", name: "imgL", widget: "image", required: false}
            -{ label: "Texte", name: "txtR", widget: "markdown", required: false}}]}
      - { label: "Body", name: "body", widget: "markdown", required: false }
